python build_index.py \
--file_path ./txt \
--neo4j_uri bolt://localhost:7687 \
--neo4j_username your_username \
--neo4j_password your_password \
--model_provider openai \
--embedding_model_name_or_path BAAI/bge-m3 \
--chat_model_name deepseek-chat \
--base_url https://api.deepseek.com \
--max_workers 16 \
--device cuda
